CREATE TABLE TODO (
    ID_TODO BIGINT not null,
    DESCRIPTION VARCHAR(255) not null,
    primary key (ID_TODO)
);

CREATE TABLE ADHERENT (
  NUMEROADHERENT INT PRIMARY KEY,
  NOM VARCHAR(255),
  PRENOM VARCHAR(255),
  ADRESSE VARCHAR(255),
  TELEPHONE VARCHAR(255),
  EMAIL VARCHAR(255) UNIQUE,
  PASSWORD VARCHAR(255)
);

CREATE TABLE TOURNOI (
 CODETOURNOI INT PRIMARY KEY,
 NOM VARCHAR(255),
 DATE DATE,
 LIEU VARCHAR(255)
);

CREATE TABLE INSCRIPTION (
 NUMEROADHERENT INT,
 CODETOURNOI INT,
 DATEINSCRIPTION DATE,
 PRIMARY KEY (NUMEROADHERENT, CODETOURNOI),
 FOREIGN KEY (CODETOURNOI) REFERENCES TOURNOI(CODETOURNOI) ON DELETE CASCADE,
 FOREIGN KEY (NUMEROADHERENT) REFERENCES ADHERENT(NUMEROADHERENT) ON DELETE CASCADE
);