services:
  myapp-mongo:
    image: myapp-mongo # name of the image
    container-name: myapp-mongo-run # name of the container
    restart: unless-stopped
    volumes:
      - "./db_docker/db_data:/data/db" # local persistent storage
      - "./db_docker/db_backup:/data/backup" # where you can save/restore
    build: ./db_docker  # cf Dockerfile in this directory
    networks:
      myapp-network:
        aliases:
          - net-db-myapp
#   ports:
#     - "127.0.0.1:27017:27017" # in case, we want to access the database outside docker from localhost
  myapp-back: # an example of an application accessing the database
    depends-on:
      - myapp-mongo
    image: myapp-back
    container-name: myapp-back-run
    restart: on-failure:2
    build: ./myapp_docker # Dockerfile (and maybe source code here)
    networks:
      myapp-network:
        aliases:
          - net-back-myapp
    ports:
      - "127.0.0.1:3000:3000" # only accessible on localhost or from outside through the ReverseProxy
    links:
      - myapp-mongo # same as depends-on
networks:
  myapp-network:
    driver: bridge
