# mysql + phpmyadmin
services:
  db:
    image: mysql
    restart: always
    env_file: .db_env
    #environment:
      # https://mariadb.com/kb/en/mariadb-docker-environment-variables/
      #MYSQL_ROOT_PASSWORD: MySecurePassword789!
      #MYSQL_DATABASE: library
      #MYSQL_USER: library 
      #MYSQL_PASSWORD: Password123!
    # SQL script that creates tables and inserts data in ./db
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "9306:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
